[project]
name = "pad-app"
version = "0.5.1"
description = "A terminal code editor for those of us who aren't into vim."
readme = "README.md"
authors = [
    { name = "Daniel Roy Greenfeld", email = "daniel@feldroy.com" }
]
requires-python = ">=3.14"
dependencies = [
    "textual[syntax]>=3.0.0",
    "typer>=0.21.0",
    "vexy-glob>=1.0.9",
]
urls.Homepage = "https://github.com/feldroy/pad-app"
urls.Issues = "https://github.com/feldroy/pad-app/issues"

[project.scripts]
pad = "pad:app"

[build-system]
requires = ["uv_build>=0.9.11,<0.10.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "pad"

[dependency-groups]
dev = [
    "pyarmor>=9.2.3",
    "pytest>=8.0.0",
    "ruff>=0.14.10",
]
